/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface RsLinearProgress {
    'buffer': number;
    'bufferbarcolor': string;
    'close': boolean;
    'progress': number;
    'progressbarcolor': string;
    'reversed': boolean;
    'setBuffer': (value: number) => Promise<void>;
    'setProgress': (value: number) => Promise<void>;
    'stylingInnerElement': (value: any) => Promise<void>;
    'type': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLRsLinearProgressElement extends Components.RsLinearProgress, HTMLStencilElement {}
  var HTMLRsLinearProgressElement: {
    prototype: HTMLRsLinearProgressElement;
    new (): HTMLRsLinearProgressElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'rs-linear-progress': HTMLRsLinearProgressElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface RsLinearProgress extends JSXBase.HTMLAttributes<HTMLRsLinearProgressElement> {
    'buffer'?: number;
    'bufferbarcolor'?: string;
    'close'?: boolean;
    'progress'?: number;
    'progressbarcolor'?: string;
    'reversed'?: boolean;
    'type'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'rs-linear-progress': RsLinearProgress;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


